language: java
jdk:
  - openjdk13

#services:
#  - postgresql
#
#before_install:
#  - psql -c 'create database spammer;' -U postgres

cache:
  directories:
    - $HOME/.m2

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -youcanwriteme@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="13cb84b3-e681-4dd5-80bf-1f1f97a0a3f9"